from setuptools import setup, find_packages

setup(
    name='TradingView_hemangmonga',
    version='0.0.1',
    description='Package to fetch live data from trading view',
    author='Hemang Monga',
    packages=find_packages(),
    install_requires=[
        'certifi==2023.5.7',
        'cffi==1.15.1',
        'charset-normalizer==3.1.0',
        'gevent==22.10.2',
        'greenlet==2.0.2',
        'idna==3.4',
        'numpy==1.24.3',
        'pandas',
        'pandas-ta==0.3.14b0',
        'pycparser==2.21',
        'python-dateutil==2.8.2',
        'pytz==2023.3',
        'requests==2.30.0',
        'six==1.16.0',
        'tzdata==2023.3',
        'urllib3==2.0.2',
        'websocket==0.2.1',
        'websocket-client==0.44.0',
        'zope.event==4.6',
        'zope.interface==6.0',
    ],
)
